//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceModelProject {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceModelProject() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DPO.Resources.Model.ResourceModelProject", typeof(ResourceModelProject).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name already in use. .
        /// </summary>
        public static string MP001 {
            get {
                return ResourceManager.GetString("MP001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Estimated Close Date can&apos;t be less than Bid Date..
        /// </summary>
        public static string MP002 {
            get {
                return ResourceManager.GetString("MP002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Bid Date can&apos;t be less than Project Registration Date..
        /// </summary>
        public static string MP003 {
            get {
                return ResourceManager.GetString("MP003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project is not accessible..
        /// </summary>
        public static string MP004 {
            get {
                return ResourceManager.GetString("MP004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote is not accessible..
        /// </summary>
        public static string MP005 {
            get {
                return ResourceManager.GetString("MP005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Estimated Delivery Date can&apos;t be less than Close Date..
        /// </summary>
        public static string MP006 {
            get {
                return ResourceManager.GetString("MP006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active quote cannot be deleted..
        /// </summary>
        public static string MP007 {
            get {
                return ResourceManager.GetString("MP007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project does not exist..
        /// </summary>
        public static string MP008 {
            get {
                return ResourceManager.GetString("MP008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote does not exist..
        /// </summary>
        public static string MP009 {
            get {
                return ResourceManager.GetString("MP009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote item does not exit..
        /// </summary>
        public static string MP010 {
            get {
                return ResourceManager.GetString("MP010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Registration  Date can&apos;t be changed once project has been created..
        /// </summary>
        public static string MP011 {
            get {
                return ResourceManager.GetString("MP011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project must be open before updates are allowed..
        /// </summary>
        public static string MP012 {
            get {
                return ResourceManager.GetString("MP012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a value..
        /// </summary>
        public static string MP013 {
            get {
                return ResourceManager.GetString("MP013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is not authorised to use the commission model pricing scheme..
        /// </summary>
        public static string MP014 {
            get {
                return ResourceManager.GetString("MP014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy/sell model not possible..
        /// </summary>
        public static string MP015 {
            get {
                return ResourceManager.GetString("MP015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total list price of commissionable products must exceed {0:C} to use this multiplier..
        /// </summary>
        public static string MP016 {
            get {
                return ResourceManager.GetString("MP016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplier value for this commission based quote is outside permitted range, or invalid..
        /// </summary>
        public static string MP017 {
            get {
                return ResourceManager.GetString("MP017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product list total has exceed the threshold of {0:C}. Quote must switch to commission scheme..
        /// </summary>
        public static string MP018 {
            get {
                return ResourceManager.GetString("MP018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote contains non commissionable products. Please remove these to use commission scheme..
        /// </summary>
        public static string MP019 {
            get {
                return ResourceManager.GetString("MP019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project must be open before quote updates are allowed..
        /// </summary>
        public static string MP020 {
            get {
                return ResourceManager.GetString("MP020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product {0} is no longer pricing or invalid, please remove the product from the the quote..
        /// </summary>
        public static string MP021 {
            get {
                return ResourceManager.GetString("MP021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket has no quote assigned to it..
        /// </summary>
        public static string MP022 {
            get {
                return ResourceManager.GetString("MP022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported product number &apos;{0}&apos; not found so record was ignored..
        /// </summary>
        public static string MP023 {
            get {
                return ResourceManager.GetString("MP023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please go to a quote you wish to import to before you import..
        /// </summary>
        public static string MP024 {
            get {
                return ResourceManager.GetString("MP024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful import of  {0} records..
        /// </summary>
        public static string MP025 {
            get {
                return ResourceManager.GetString("MP025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File being attached is too big, Max allowed {0}Mb..
        /// </summary>
        public static string MP026 {
            get {
                return ResourceManager.GetString("MP026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project has been transferred, no edits allowed..
        /// </summary>
        public static string MP027 {
            get {
                return ResourceManager.GetString("MP027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No edits are allowed once a discount request has been assigned to the quote..
        /// </summary>
        public static string MP028 {
            get {
                return ResourceManager.GetString("MP028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitors&apos; price required..
        /// </summary>
        public static string MP100 {
            get {
                return ResourceManager.GetString("MP100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a competitor quote file to upload..
        /// </summary>
        public static string MP101 {
            get {
                return ResourceManager.GetString("MP101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a competitor line by line comparsion file to upload..
        /// </summary>
        public static string MP102 {
            get {
                return ResourceManager.GetString("MP102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote currently has a discount request waiting for approval..
        /// </summary>
        public static string MP103 {
            get {
                return ResourceManager.GetString("MP103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote already assigned a discount request. .
        /// </summary>
        public static string MP104 {
            get {
                return ResourceManager.GetString("MP104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter percentages requested..
        /// </summary>
        public static string MP105 {
            get {
                return ResourceManager.GetString("MP105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a reason for requesting the discount..
        /// </summary>
        public static string MP106 {
            get {
                return ResourceManager.GetString("MP106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a reason..
        /// </summary>
        public static string MP107 {
            get {
                return ResourceManager.GetString("MP107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a System Basis Of Design.
        /// </summary>
        public static string MP108 {
            get {
                return ResourceManager.GetString("MP108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Zone Strategy.
        /// </summary>
        public static string MP109 {
            get {
                return ResourceManager.GetString("MP109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Specified Brand.
        /// </summary>
        public static string MP110 {
            get {
                return ResourceManager.GetString("MP110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an Approved Equals.
        /// </summary>
        public static string MP111 {
            get {
                return ResourceManager.GetString("MP111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an issue date.
        /// </summary>
        public static string MP112 {
            get {
                return ResourceManager.GetString("MP112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an approximate delivery date.
        /// </summary>
        public static string MP113 {
            get {
                return ResourceManager.GetString("MP113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an option.
        /// </summary>
        public static string MP114 {
            get {
                return ResourceManager.GetString("MP114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a probability of close percentage.
        /// </summary>
        public static string MP115 {
            get {
                return ResourceManager.GetString("MP115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change Project Status to Closed while a Discount Request is pending.
        /// </summary>
        public static string MP116 {
            get {
                return ResourceManager.GetString("MP116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC Email is not a valid Daikin City user.
        /// </summary>
        public static string MP117 {
            get {
                return ResourceManager.GetString("MP117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Pricing Type.
        /// </summary>
        public static string MP118 {
            get {
                return ResourceManager.GetString("MP118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter PO Number.
        /// </summary>
        public static string MP119 {
            get {
                return ResourceManager.GetString("MP119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Project Bid Date.
        /// </summary>
        public static string MP120 {
            get {
                return ResourceManager.GetString("MP120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Estimate Close Date.
        /// </summary>
        public static string MP121 {
            get {
                return ResourceManager.GetString("MP121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Delivery Contact Name.
        /// </summary>
        public static string MP122 {
            get {
                return ResourceManager.GetString("MP122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Delivery Contact Number.
        /// </summary>
        public static string MP123 {
            get {
                return ResourceManager.GetString("MP123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Order Submit Email.
        /// </summary>
        public static string MP124 {
            get {
                return ResourceManager.GetString("MP124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a PO Number.
        /// </summary>
        public static string MP125 {
            get {
                return ResourceManager.GetString("MP125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Attachment is not created.
        /// </summary>
        public static string MP126 {
            get {
                return ResourceManager.GetString("MP126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Order Attachment.
        /// </summary>
        public static string MP127 {
            get {
                return ResourceManager.GetString("MP127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate Release Date must  be set to 10 days before Estimate Delivery Date.
        /// </summary>
        public static string MP128 {
            get {
                return ResourceManager.GetString("MP128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not Submit Order.Project Open Status is either Inactive or Closed-Losted..
        /// </summary>
        public static string MP129 {
            get {
                return ResourceManager.GetString("MP129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Order can only be submit one time.You can not resubmit same Order..
        /// </summary>
        public static string MP130 {
            get {
                return ResourceManager.GetString("MP130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote must be Buy/Sell in order to Submit.
        /// </summary>
        public static string MP131 {
            get {
                return ResourceManager.GetString("MP131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote must be set to Active before submit Order.
        /// </summary>
        public static string MP132 {
            get {
                return ResourceManager.GetString("MP132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Order Release Date .
        /// </summary>
        public static string MP133 {
            get {
                return ResourceManager.GetString("MP133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Release Date must be greater than Order Submit Date..
        /// </summary>
        public static string MP134 {
            get {
                return ResourceManager.GetString("MP134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order does not have any Order Item.Please add items to Order.
        /// </summary>
        public static string MP135 {
            get {
                return ResourceManager.GetString("MP135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Quantity is 0. .
        /// </summary>
        public static string MP136 {
            get {
                return ResourceManager.GetString("MP136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide some comments.
        /// </summary>
        public static string MP137 {
            get {
                return ResourceManager.GetString("MP137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Delivery Contact Name.
        /// </summary>
        public static string MP138 {
            get {
                return ResourceManager.GetString("MP138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Delivery Contact Phone.
        /// </summary>
        public static string MP139 {
            get {
                return ResourceManager.GetString("MP139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to calculate commission. No quote found..
        /// </summary>
        public static string MP140 {
            get {
                return ResourceManager.GetString("MP140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file format.  Please try a different file..
        /// </summary>
        public static string MP141 {
            get {
                return ResourceManager.GetString("MP141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot process Order. Found error on Product Number: {0}. Please contact Daikin..
        /// </summary>
        public static string MP142 {
            get {
                return ResourceManager.GetString("MP142", resourceCulture);
            }
        }
    }
}
