//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceModelUser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceModelUser() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DPO.Resources.Model.ResourceModelUser", typeof(ResourceModelUser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email already in use. Please choose another email address..
        /// </summary>
        public static string MU001 {
            get {
                return ResourceManager.GetString("MU001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user address is empty. Contact system support..
        /// </summary>
        public static string MU002 {
            get {
                return ResourceManager.GetString("MU002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user contact is empty. Contact system support..
        /// </summary>
        public static string MU003 {
            get {
                return ResourceManager.GetString("MU003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password invalid..
        /// </summary>
        public static string MU004 {
            get {
                return ResourceManager.GetString("MU004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to login user has been disabled. Please contact customer services..
        /// </summary>
        public static string MU005 {
            get {
                return ResourceManager.GetString("MU005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to login user awaiting approval..
        /// </summary>
        public static string MU006 {
            get {
                return ResourceManager.GetString("MU006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not found..
        /// </summary>
        public static string MU007 {
            get {
                return ResourceManager.GetString("MU007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email has a secure reset link. The link is only valid for 30 minutes. Please press the link button to proceed..
        /// </summary>
        public static string MU008 {
            get {
                return ResourceManager.GetString("MU008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The security email has timed out or is invalid. Please request another password reset..
        /// </summary>
        public static string MU009 {
            get {
                return ResourceManager.GetString("MU009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password does not match the password entered..
        /// </summary>
        public static string MU010 {
            get {
                return ResourceManager.GetString("MU010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset. To use the system you need to login again..
        /// </summary>
        public static string MU011 {
            get {
                return ResourceManager.GetString("MU011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} has been approved, and approval email sent..
        /// </summary>
        public static string MU012 {
            get {
                return ResourceManager.GetString("MU012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been enabled..
        /// </summary>
        public static string MU013 {
            get {
                return ResourceManager.GetString("MU013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been disabled..
        /// </summary>
        public static string MU014 {
            get {
                return ResourceManager.GetString("MU014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a user type..
        /// </summary>
        public static string MU015 {
            get {
                return ResourceManager.GetString("MU015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket Cleared.
        /// </summary>
        public static string MU016 {
            get {
                return ResourceManager.GetString("MU016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item added to basket.
        /// </summary>
        public static string MU017 {
            get {
                return ResourceManager.GetString("MU017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item removed from basket.
        /// </summary>
        public static string MU018 {
            get {
                return ResourceManager.GetString("MU018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item quantity adjusted..
        /// </summary>
        public static string MU019 {
            get {
                return ResourceManager.GetString("MU019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote not accessible..
        /// </summary>
        public static string MU020 {
            get {
                return ResourceManager.GetString("MU020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user business is empty. Contact system support..
        /// </summary>
        public static string MU021 {
            get {
                return ResourceManager.GetString("MU021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to login business has been disabled. Please contact customer services..
        /// </summary>
        public static string MU022 {
            get {
                return ResourceManager.GetString("MU022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your business has not been enabled for Daikin City. Please contact customer service to ensure your business is setup correctly..
        /// </summary>
        public static string MU023 {
            get {
                return ResourceManager.GetString("MU023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email is empty.
        /// </summary>
        public static string MU024 {
            get {
                return ResourceManager.GetString("MU024", resourceCulture);
            }
        }
    }
}
