//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceModelBusiness {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceModelBusiness() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DPO.Resources.Model.ResourceModelBusiness", typeof(ResourceModelBusiness).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Id is invalid or has not been set up. Please contact Daikin to set up the account or to get the correct account Id..
        /// </summary>
        public static string BM001 {
            get {
                return ResourceManager.GetString("BM001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Id has been assigned already and is in use..
        /// </summary>
        public static string BM003 {
            get {
                return ResourceManager.GetString("BM003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business name already in use. Please choose another business name..
        /// </summary>
        public static string BM004 {
            get {
                return ResourceManager.GetString("BM004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business type is required..
        /// </summary>
        public static string BM005 {
            get {
                return ResourceManager.GetString("BM005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authorised to change busines type..
        /// </summary>
        public static string BM006 {
            get {
                return ResourceManager.GetString("BM006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business account must exist for this type of business..
        /// </summary>
        public static string BM007 {
            get {
                return ResourceManager.GetString("BM007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s Business does not has ShowPricing permit.
        /// </summary>
        public static string BM008 {
            get {
                return ResourceManager.GetString("BM008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not submit Order.Business does not have ERP Account.
        /// </summary>
        public static string BM009 {
            get {
                return ResourceManager.GetString("BM009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERPAccountId can not be empty.
        /// </summary>
        public static string BM010 {
            get {
                return ResourceManager.GetString("BM010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PONumber already exists in Daikin Database.
        /// </summary>
        public static string BM011 {
            get {
                return ResourceManager.GetString("BM011", resourceCulture);
            }
        }
    }
}
