//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceModelUserGroups {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceModelUserGroups() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DPO.Resources.Model.ResourceModelUserGroups", typeof(ResourceModelUserGroups).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name is empty or invalid..
        /// </summary>
        public static string UG001 {
            get {
                return ResourceManager.GetString("UG001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorised to move users into that group..
        /// </summary>
        public static string UG002 {
            get {
                return ResourceManager.GetString("UG002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorised to move the user from their group..
        /// </summary>
        public static string UG003 {
            get {
                return ResourceManager.GetString("UG003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users moved to group..
        /// </summary>
        public static string UG004 {
            get {
                return ResourceManager.GetString("UG004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group access required..
        /// </summary>
        public static string UG005 {
            get {
                return ResourceManager.GetString("UG005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot make a child group the parent group..
        /// </summary>
        public static string UG006 {
            get {
                return ResourceManager.GetString("UG006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent group access required..
        /// </summary>
        public static string UG007 {
            get {
                return ResourceManager.GetString("UG007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorised to delete the group..
        /// </summary>
        public static string UG009 {
            get {
                return ResourceManager.GetString("UG009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group cannot be removed while it has users assigned to it..
        /// </summary>
        public static string UG010 {
            get {
                return ResourceManager.GetString("UG010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group cannot be deleted while it has child groups assigned to it..
        /// </summary>
        public static string UG011 {
            get {
                return ResourceManager.GetString("UG011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Group invalid.
        /// </summary>
        public static string UG012 {
            get {
                return ResourceManager.GetString("UG012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group cannot have itself as parent.
        /// </summary>
        public static string UG013 {
            get {
                return ResourceManager.GetString("UG013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users cannot adjust their own group ownership..
        /// </summary>
        public static string UG014 {
            get {
                return ResourceManager.GetString("UG014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User cannot be found , is no longer part of that group ro or you are not authorised to adjust this users ownership..
        /// </summary>
        public static string UG015 {
            get {
                return ResourceManager.GetString("UG015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change ownership as user is unallocated a group..
        /// </summary>
        public static string UG016 {
            get {
                return ResourceManager.GetString("UG016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action not allowed on unallocated group..
        /// </summary>
        public static string UG017 {
            get {
                return ResourceManager.GetString("UG017", resourceCulture);
            }
        }
    }
}
