//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPO.Web.MapicsOrderService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CFG001RInput", Namespace="http://cfg001r.wsbeans.iseries/xsd")]
    [System.SerializableAttribute()]
    public partial class CFG001RInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DPO.Web.MapicsOrderService.INORDERREQ INORDERREQField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public DPO.Web.MapicsOrderService.INORDERREQ INORDERREQ {
            get {
                return this.INORDERREQField;
            }
            set {
                if ((object.ReferenceEquals(this.INORDERREQField, value) != true)) {
                    this.INORDERREQField = value;
                    this.RaisePropertyChanged("INORDERREQ");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="INORDERREQ", Namespace="http://cfg001r.wsbeans.iseries/xsd")]
    [System.SerializableAttribute()]
    public partial class INORDERREQ : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int lengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stringField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int length {
            get {
                return this.lengthField;
            }
            set {
                if ((this.lengthField.Equals(value) != true)) {
                    this.lengthField = value;
                    this.RaisePropertyChanged("length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string @string {
            get {
                return this.stringField;
            }
            set {
                if ((object.ReferenceEquals(this.stringField, value) != true)) {
                    this.stringField = value;
                    this.RaisePropertyChanged("string");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CFG001RResult", Namespace="http://cfg001r.wsbeans.iseries/xsd")]
    [System.SerializableAttribute()]
    public partial class CFG001RResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DPO.Web.MapicsOrderService.INORDERREQ INORDERREQField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public DPO.Web.MapicsOrderService.INORDERREQ INORDERREQ {
            get {
                return this.INORDERREQField;
            }
            set {
                if ((object.ReferenceEquals(this.INORDERREQField, value) != true)) {
                    this.INORDERREQField = value;
                    this.RaisePropertyChanged("INORDERREQ");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cfg001r.wsbeans.iseries", ConfigurationName="MapicsOrderService.CFG001RPortType")]
    public interface CFG001RPortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://cfg001r.wsbeans.iseries/xsd) of message cfg001rRequest does not match the default value (http://cfg001r.wsbeans.iseries)
        [System.ServiceModel.OperationContractAttribute(Action="urn:cfg001r", ReplyAction="urn:cfg001rResponse")]
        DPO.Web.MapicsOrderService.cfg001rResponse cfg001r(DPO.Web.MapicsOrderService.cfg001rRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:cfg001r", ReplyAction="urn:cfg001rResponse")]
        System.Threading.Tasks.Task<DPO.Web.MapicsOrderService.cfg001rResponse> cfg001rAsync(DPO.Web.MapicsOrderService.cfg001rRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://cfg001r.wsbeans.iseries/xsd) of message cfg001r_XMLRequest does not match the default value (http://cfg001r.wsbeans.iseries)
        [System.ServiceModel.OperationContractAttribute(Action="urn:cfg001r_XML", ReplyAction="urn:cfg001r_XMLResponse")]
        DPO.Web.MapicsOrderService.cfg001r_XMLResponse cfg001r_XML(DPO.Web.MapicsOrderService.cfg001r_XMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:cfg001r_XML", ReplyAction="urn:cfg001r_XMLResponse")]
        System.Threading.Tasks.Task<DPO.Web.MapicsOrderService.cfg001r_XMLResponse> cfg001r_XMLAsync(DPO.Web.MapicsOrderService.cfg001r_XMLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cfg001r", WrapperNamespace="http://cfg001r.wsbeans.iseries/xsd", IsWrapped=true)]
    public partial class cfg001rRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfg001r.wsbeans.iseries/xsd", Order=0)]
        public DPO.Web.MapicsOrderService.CFG001RInput args0;
        
        public cfg001rRequest() {
        }
        
        public cfg001rRequest(DPO.Web.MapicsOrderService.CFG001RInput args0) {
            this.args0 = args0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cfg001rResponse", WrapperNamespace="http://cfg001r.wsbeans.iseries/xsd", IsWrapped=true)]
    public partial class cfg001rResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfg001r.wsbeans.iseries/xsd", Order=0)]
        public DPO.Web.MapicsOrderService.CFG001RResult @return;
        
        public cfg001rResponse() {
        }
        
        public cfg001rResponse(DPO.Web.MapicsOrderService.CFG001RResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cfg001r_XML", WrapperNamespace="http://cfg001r.wsbeans.iseries/xsd", IsWrapped=true)]
    public partial class cfg001r_XMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfg001r.wsbeans.iseries/xsd", Order=0)]
        public DPO.Web.MapicsOrderService.CFG001RInput args0;
        
        public cfg001r_XMLRequest() {
        }
        
        public cfg001r_XMLRequest(DPO.Web.MapicsOrderService.CFG001RInput args0) {
            this.args0 = args0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cfg001r_XMLResponse", WrapperNamespace="http://cfg001r.wsbeans.iseries/xsd", IsWrapped=true)]
    public partial class cfg001r_XMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfg001r.wsbeans.iseries/xsd", Order=0)]
        public string @return;
        
        public cfg001r_XMLResponse() {
        }
        
        public cfg001r_XMLResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CFG001RPortTypeChannel : DPO.Web.MapicsOrderService.CFG001RPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CFG001RPortTypeClient : System.ServiceModel.ClientBase<DPO.Web.MapicsOrderService.CFG001RPortType>, DPO.Web.MapicsOrderService.CFG001RPortType {
        
        public CFG001RPortTypeClient() {
        }
        
        public CFG001RPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CFG001RPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CFG001RPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CFG001RPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DPO.Web.MapicsOrderService.cfg001rResponse DPO.Web.MapicsOrderService.CFG001RPortType.cfg001r(DPO.Web.MapicsOrderService.cfg001rRequest request) {
            return base.Channel.cfg001r(request);
        }
        
        public DPO.Web.MapicsOrderService.CFG001RResult cfg001r(DPO.Web.MapicsOrderService.CFG001RInput args0) {
            DPO.Web.MapicsOrderService.cfg001rRequest inValue = new DPO.Web.MapicsOrderService.cfg001rRequest();
            inValue.args0 = args0;
            DPO.Web.MapicsOrderService.cfg001rResponse retVal = ((DPO.Web.MapicsOrderService.CFG001RPortType)(this)).cfg001r(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DPO.Web.MapicsOrderService.cfg001rResponse> DPO.Web.MapicsOrderService.CFG001RPortType.cfg001rAsync(DPO.Web.MapicsOrderService.cfg001rRequest request) {
            return base.Channel.cfg001rAsync(request);
        }
        
        public System.Threading.Tasks.Task<DPO.Web.MapicsOrderService.cfg001rResponse> cfg001rAsync(DPO.Web.MapicsOrderService.CFG001RInput args0) {
            DPO.Web.MapicsOrderService.cfg001rRequest inValue = new DPO.Web.MapicsOrderService.cfg001rRequest();
            inValue.args0 = args0;
            return ((DPO.Web.MapicsOrderService.CFG001RPortType)(this)).cfg001rAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DPO.Web.MapicsOrderService.cfg001r_XMLResponse DPO.Web.MapicsOrderService.CFG001RPortType.cfg001r_XML(DPO.Web.MapicsOrderService.cfg001r_XMLRequest request) {
            return base.Channel.cfg001r_XML(request);
        }
        
        public string cfg001r_XML(DPO.Web.MapicsOrderService.CFG001RInput args0) {
            DPO.Web.MapicsOrderService.cfg001r_XMLRequest inValue = new DPO.Web.MapicsOrderService.cfg001r_XMLRequest();
            inValue.args0 = args0;
            DPO.Web.MapicsOrderService.cfg001r_XMLResponse retVal = ((DPO.Web.MapicsOrderService.CFG001RPortType)(this)).cfg001r_XML(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DPO.Web.MapicsOrderService.cfg001r_XMLResponse> DPO.Web.MapicsOrderService.CFG001RPortType.cfg001r_XMLAsync(DPO.Web.MapicsOrderService.cfg001r_XMLRequest request) {
            return base.Channel.cfg001r_XMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<DPO.Web.MapicsOrderService.cfg001r_XMLResponse> cfg001r_XMLAsync(DPO.Web.MapicsOrderService.CFG001RInput args0) {
            DPO.Web.MapicsOrderService.cfg001r_XMLRequest inValue = new DPO.Web.MapicsOrderService.cfg001r_XMLRequest();
            inValue.args0 = args0;
            return ((DPO.Web.MapicsOrderService.CFG001RPortType)(this)).cfg001r_XMLAsync(inValue);
        }
    }
}
