#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DPO.Common;
    using DPO.Resources;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ProjectDashboard/ProjectButtonBar.cshtml")]
    public partial class _Views_ProjectDashboard_ProjectButtonBar_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_ProjectDashboard_ProjectButtonBar_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\ProjectDashboard\ProjectButtonBar.cshtml"
  
    var user = ViewData["CurrentUser"] as UserSessionModel;
    var exportProjectStatus = ViewData["exportProjectStatus"] as string;

            
            #line default
            #line hidden
WriteLiteral("\n<div");

WriteLiteral(" class=\"btn-bar\"");

WriteLiteral(">\n");

            
            #line 6 "..\..\Views\ProjectDashboard\ProjectButtonBar.cshtml"
    
            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\ProjectDashboard\ProjectButtonBar.cshtml"
     if (user.HasAccess(SystemAccessEnum.UndeleteProject) && Model.Deleted)
    {

            
            #line default
            #line hidden
WriteLiteral("        <a");

WriteLiteral(" href=\"#\"");

WriteAttribute("sc-ajaxpost", Tuple.Create(" sc-ajaxpost=\"", 262), Tuple.Create("\"", 306)
            
            #line 8 "..\..\Views\ProjectDashboard\ProjectButtonBar.cshtml"
, Tuple.Create(Tuple.Create("", 276), Tuple.Create<System.Object, System.Int32>(Url.Action("ProjectUndelete")
            
            #line default
            #line hidden
, 276), false)
);

WriteLiteral(" class=\"btn h-slim\"");

WriteLiteral(">\n            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 344), Tuple.Create("\"", 386)
, Tuple.Create(Tuple.Create("", 350), Tuple.Create<System.Object, System.Int32>(Href("~/Images/context-btn-delete-icon.png")
, 350), false)
);

WriteLiteral(" />\n");

WriteLiteral("            ");

            
            #line 10 "..\..\Views\ProjectDashboard\ProjectButtonBar.cshtml"
       Write(ResourceUI.ProjectUndelete);

            
            #line default
            #line hidden
WriteLiteral("\n        </a>\n");

            
            #line 12 "..\..\Views\ProjectDashboard\ProjectButtonBar.cshtml"
    }
    else if (Model.Deleted == false)
    {
            if (user.HasAccess(SystemAccessEnum.RequestDiscounts)
                && Model.IsTransferred == false
                && Model.ActiveQuoteSummary.HasDAR == false
                && Model.ActiveQuoteSummary.HasCOM == false
                && user.ShowPrices
                && Model.ActiveQuoteSummary.QuoteId > 0
                && Model.ProjectStatusTypeId == (int)ProjectStatusTypeEnum.Open)
            {
                
            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\ProjectDashboard\ProjectButtonBar.cshtml"
                   
               
                
               
            
            #line default
            #line hidden
            
            #line 43 "..\..\Views\ProjectDashboard\ProjectButtonBar.cshtml"
                     

            }

            if (user.HasAccess(SystemAccessEnum.RequestCommission)
                && Model.IsTransferred == false
                && Model.ActiveQuoteSummary.HasDAR == false
                && Model.ActiveQuoteSummary.HasCOM == false
                && user.ShowPrices
                && Model.ActiveQuoteSummary.QuoteId > 0
                && Model.ProjectStatusTypeId == (int)ProjectStatusTypeEnum.Open
                && Model.ProjectStatusTypeId != (int)ProjectStatusTypeEnum.Inactive 
                && Model.OrderStatus != (byte)OrderStatusTypeEnum.AwaitingCSR 
                && Model.OrderStatus != (byte)OrderStatusTypeEnum.Submitted)
            {
                if (Model.ActiveQuoteSummary.IsCommission)
                {
                    
            
            #line default
            #line hidden
            
            #line 64 "..\..\Views\ProjectDashboard\ProjectButtonBar.cshtml"
                          
                }
                
            
            #line default
            #line hidden
            
            #line 72 "..\..\Views\ProjectDashboard\ProjectButtonBar.cshtml"
                   

            }


            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3821), Tuple.Create("\"", 3913)
            
            #line 76 "..\..\Views\ProjectDashboard\ProjectButtonBar.cshtml"
, Tuple.Create(Tuple.Create("", 3828), Tuple.Create<System.Object, System.Int32>(Url.Action("ProjectExport", "Projectdashboard", new { ProjectId = Model.ProjectId })
            
            #line default
            #line hidden
, 3828), false)
);

WriteLiteral(" class=\"btn h-slim\"");

WriteLiteral(">\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 3955), Tuple.Create("\"", 3992)
, Tuple.Create(Tuple.Create("", 3961), Tuple.Create<System.Object, System.Int32>(Href("~/Images/package-quote-icon.png")
, 3961), false)
);

WriteLiteral(" />\n");

WriteLiteral("                ");

            
            #line 78 "..\..\Views\ProjectDashboard\ProjectButtonBar.cshtml"
           Write(ResourceUI.Export);

            
            #line default
            #line hidden
WriteLiteral("\n            </a>\n");

            
            #line 80 "..\..\Views\ProjectDashboard\ProjectButtonBar.cshtml"
            if (user.HasAccess(SystemAccessEnum.EditProject) && Model.IsTransferred == false)
            { 

            
            #line default
            #line hidden
WriteLiteral("                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-confirm=\"ProjectDelete\"");

WriteLiteral(" data-sc-ajaxpost=\"");

            
            #line 82 "..\..\Views\ProjectDashboard\ProjectButtonBar.cshtml"
                                                                      Write(Url.Action("ProjectDelete"));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" class=\"btn h-slim\"");

WriteLiteral(">\n                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 4307), Tuple.Create("\"", 4349)
, Tuple.Create(Tuple.Create("", 4313), Tuple.Create<System.Object, System.Int32>(Href("~/Images/context-btn-delete-icon.png")
, 4313), false)
);

WriteLiteral(" />\n");

WriteLiteral("                    ");

            
            #line 84 "..\..\Views\ProjectDashboard\ProjectButtonBar.cshtml"
               Write(ResourceUI.ProjectDelete);

            
            #line default
            #line hidden
WriteLiteral("\n                </a>\r\n");

            
            #line 86 "..\..\Views\ProjectDashboard\ProjectButtonBar.cshtml"

               
        }

    }
    
    
            
            #line default
            #line hidden
            
            #line 92 "..\..\Views\ProjectDashboard\ProjectButtonBar.cshtml"
                                                                  

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 93 "..\..\Views\ProjectDashboard\ProjectButtonBar.cshtml"
     if (exportProjectStatus != null)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" id=\"exportProjectStatus\"");

WriteLiteral(" style=\"display:none\"");

WriteAttribute("status", Tuple.Create(" status=\"", 4636), Tuple.Create("\"", 4665)
            
            #line 95 "..\..\Views\ProjectDashboard\ProjectButtonBar.cshtml"
, Tuple.Create(Tuple.Create("", 4645), Tuple.Create<System.Object, System.Int32>(exportProjectStatus
            
            #line default
            #line hidden
, 4645), false)
);

WriteLiteral(">");

            
            #line 95 "..\..\Views\ProjectDashboard\ProjectButtonBar.cshtml"
                                                                                    Write(exportProjectStatus);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 96 "..\..\Views\ProjectDashboard\ProjectButtonBar.cshtml"

    }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
