
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class Building

{

    public int BuildingId { get; set; }

    public string Name { get; set; }

    public int TypeId { get; set; }

    public string VideoIn { get; set; }

    public string VideoInPoster { get; set; }

    public string HotSpotX { get; set; }

    public string HotSpotY { get; set; }

    public string MenuImage { get; set; }

    public string BuildingFolderName { get; set; }

}

}
