
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class BuildingFloorConfiguration

{

    public int FloorConfigId { get; set; }

    public string Name { get; set; }

    public string SystemName { get; set; }

    public string SystemSize { get; set; }

    public string Energy { get; set; }

    public int FloorId { get; set; }

    public string OverlayImage { get; set; }

    public string SystemImage { get; set; }

    public string SystemType { get; set; }

    public Nullable<bool> Alternate { get; set; }

}

}
