
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class BusinessType

{

    public BusinessType()
    {

        this.Businesses = new HashSet<Business>();

    }


    public DPO.Common.BusinessTypeEnum BusinessTypeId { get; set; }

    public string Description { get; set; }

    public Nullable<byte> BusinessIdRequirementLevelId { get; set; }



    public virtual ICollection<Business> Businesses { get; set; }

    public virtual RequirementLevel RequirementLevel { get; set; }

}

}
