
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class C_TestUserGroups
 : IConcurrency 
{

    public long GroupId { get; set; }

    public Nullable<long> ParentGroupId { get; set; }

    public string Name { get; set; }

    public Nullable<System.Guid> DaikinGroupId { get; set; }

    public string Path { get; set; }

    public short ChildrenCount { get; set; }

    public short ChildrenCountDeep { get; set; }

    public short MemberCount { get; set; }

    public string WBS { get; set; }

    public System.DateTime Timestamp { get; set; }

}

}
