
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class CommissionRequest
 : IConcurrency 
{

    public CommissionRequest()
    {

        this.CommissionCalculations = new HashSet<CommissionCalculation>();

        this.Orders = new HashSet<Order>();

    }


    public long CommissionRequestId { get; set; }

    public long ProjectId { get; set; }

    public long QuoteId { get; set; }

    public decimal StartUpCosts { get; set; }

    public decimal RequestedCommission { get; set; }

    public System.DateTime RequestedOn { get; set; }

    public Nullable<byte> CommissionRequestStatusTypeId { get; set; }

    public System.DateTime StatusTypeModifiedOn { get; set; }

    public Nullable<long> StatusTypeModifiedBy { get; set; }

    public Nullable<byte> SystemBasisDesignTypeId { get; set; }

    public Nullable<byte> ZoneStrategyTypeId { get; set; }

    public Nullable<byte> BrandSpecifiedTypeId { get; set; }

    public Nullable<byte> BrandApprovedTypeId { get; set; }

    public bool HasCompetitorPrice { get; set; }

    public Nullable<decimal> CompetitorPrice { get; set; }

    public bool HasCompetitorQuote { get; set; }

    public string CompetitorQuoteFileName { get; set; }

    public bool HasCompetitorLineComparsion { get; set; }

    public string CompetitorLineComparsionFileName { get; set; }

    public bool IsConfidentCompetitorQuote { get; set; }

    public bool ApprovalAssuresOrder { get; set; }

    public Nullable<System.DateTime> OrderPlannedFor { get; set; }

    public Nullable<System.DateTime> OrderDeliveryDate { get; set; }

    public string Notes { get; set; }

    public string ResponseNotes { get; set; }

    public System.DateTime Timestamp { get; set; }

    public Nullable<byte> DaikinEquipmentAtAdvantageTypeId { get; set; }

    public Nullable<byte> ProbabilityOfCloseTypeId { get; set; }

    public Nullable<decimal> ApprovedMultiplier { get; set; }

    public Nullable<decimal> ApprovedMultiplierSplit { get; set; }

    public Nullable<decimal> ApprovedMultiplierVRV { get; set; }

    public Nullable<decimal> RequestedCommissionPercent { get; set; }

    public Nullable<decimal> RequestedCommissionPercentVRV { get; set; }

    public Nullable<decimal> RequestedCommissionPercentSplit { get; set; }

    public Nullable<decimal> ApprovedCommissionPercent { get; set; }

    public Nullable<decimal> ApprovedCommissionPercentVRV { get; set; }

    public Nullable<decimal> ApprovedCommissionPercentSplit { get; set; }

    public string EmailsList { get; set; }

    public Nullable<decimal> RequestedMultiplier { get; set; }

    public Nullable<decimal> RequestedMultiplierVRV { get; set; }

    public Nullable<decimal> RequestedMultiplierSplit { get; set; }

    public Nullable<long> DiscountRequestId { get; set; }

    public Nullable<int> WinLossTypeId { get; set; }

    public Nullable<byte> FundingTypeId { get; set; }

    public Nullable<byte> CustomerTypeId { get; set; }

    public string RepPhoneNumber { get; set; }

    public string SellerPhoneNumber { get; set; }

    public string RepEmail { get; set; }

    public string SellerEmail { get; set; }

    public string RepFaxNumber { get; set; }

    public string SellerFaxNumber { get; set; }

    public Nullable<bool> IsCommissionCalculation { get; set; }

    public Nullable<decimal> RequestedCommissionVRV { get; set; }

    public Nullable<decimal> RequestedCommissionSplit { get; set; }

    public Nullable<decimal> RequestedCommissionTotal { get; set; }

    public Nullable<decimal> RequestedNetMaterialMultiplierVRV { get; set; }

    public Nullable<decimal> RequestedNetMaterialMultiplierSplit { get; set; }

    public Nullable<decimal> RequestedNetMultiplierValueVRV { get; set; }

    public Nullable<decimal> RequestedNetMultiplierValueSplit { get; set; }

    public Nullable<decimal> RequestedNetMaterialValueMultiplier { get; set; }

    public Nullable<decimal> RequestedNetMaterialValue { get; set; }

    public Nullable<decimal> TotalListVRV { get; set; }

    public Nullable<decimal> TotalListSplit { get; set; }

    public Nullable<decimal> TotalNetVRV { get; set; }

    public Nullable<decimal> TotalNetSplit { get; set; }

    public Nullable<decimal> TotalNet { get; set; }

    public Nullable<decimal> ApprovedCommissionTotal { get; set; }

    public Nullable<decimal> TotalRevised { get; set; }

    public Nullable<decimal> ThirdPartyEquipmentCosts { get; set; }

    public Nullable<decimal> RequestedCommissionUnitary { get; set; }

    public Nullable<decimal> RequestedMultiplierUnitary { get; set; }

    public Nullable<decimal> RequestedCommissionPercentUnitary { get; set; }

    public Nullable<decimal> ApprovedCommissionPercentUnitary { get; set; }

    public Nullable<decimal> ApprovedMultiplierUnitary { get; set; }

    public Nullable<decimal> RequestedNetMaterialMultiplierUnitary { get; set; }

    public Nullable<decimal> RequestedNetMultiplierValueUnitary { get; set; }

    public Nullable<decimal> TotalListUnitary { get; set; }

    public Nullable<decimal> TotalNetUnitary { get; set; }

    public Nullable<decimal> RequestedMultiplierLCPackage { get; set; }

    public Nullable<decimal> RequestedCommissionLCPackage { get; set; }

    public Nullable<decimal> RequestedCommissionPercentLCPackage { get; set; }

    public Nullable<decimal> ApprovedCommissionPercentLCPackage { get; set; }

    public Nullable<decimal> RequestedNetMaterialMultiplierLCPackage { get; set; }

    public Nullable<decimal> RequestedNetMultiplierValueLCPackage { get; set; }

    public Nullable<decimal> ApprovedMultiplierLCPackage { get; set; }

    public Nullable<decimal> TotalListLCPackage { get; set; }

    public Nullable<decimal> TotalNetLCPackage { get; set; }



    public virtual BrandCompetitorType BrandApprovedType { get; set; }

    public virtual BrandCompetitorType BrandSpecifiedType { get; set; }

    public virtual Quote Quote { get; set; }

    public virtual SystemBasisDesignType SystemBasisDesignType { get; set; }

    public virtual ZoneStrategyType ZoneStrategyType { get; set; }

    public virtual CommissionRequestStatusType CommissionRequestStatusType { get; set; }

    public virtual CommissionRequest CommissionRequests1 { get; set; }

    public virtual CommissionRequest CommissionRequest1 { get; set; }

    public virtual CommissionRequest CommissionRequests11 { get; set; }

    public virtual CommissionRequest CommissionRequest2 { get; set; }

    public virtual CustomerType CustomerType { get; set; }

    public virtual FundingType FundingType { get; set; }

    public virtual WinLossType WinLossType { get; set; }

    public virtual ICollection<CommissionCalculation> CommissionCalculations { get; set; }

    public virtual Project Project { get; set; }

    public virtual ICollection<Order> Orders { get; set; }

}

}
