
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class CommissionCalculation

{

    public long CommissionCalculationId { get; set; }

    public Nullable<long> CommissionRequestId { get; set; }

    public long ProjectId { get; set; }

    public long QuoteId { get; set; }

    public Nullable<decimal> VRVPercentage { get; set; }

    public Nullable<decimal> SplitPercentage { get; set; }

    public Nullable<decimal> VRVMultiplier { get; set; }

    public Nullable<decimal> SplitMultiplier { get; set; }

    public Nullable<decimal> CommissionAmountVRV { get; set; }

    public Nullable<decimal> CommissionAmountSplit { get; set; }

    public Nullable<decimal> NetMultiplierVRV { get; set; }

    public Nullable<decimal> NetMultiplierSplit { get; set; }

    public Nullable<decimal> NetMaterialValueVRV { get; set; }

    public Nullable<decimal> TotalListVRV { get; set; }

    public Nullable<decimal> TotalListSplit { get; set; }

    public Nullable<decimal> NetMaterialValueSplit { get; set; }

    public Nullable<decimal> CommissionTotalPercentage { get; set; }

    public Nullable<decimal> TotalCommissionAmount { get; set; }

    public Nullable<decimal> TotalNetMaterialValueMultiplier { get; set; }

    public Nullable<decimal> TotalNetMaterialValue { get; set; }

    public Nullable<decimal> TotalList { get; set; }

    public Nullable<decimal> UnitaryPercentage { get; set; }

    public Nullable<decimal> UnitaryMultiplier { get; set; }

    public Nullable<decimal> CommissionAmountUnitary { get; set; }

    public Nullable<decimal> NetMultiplierUnitary { get; set; }

    public Nullable<decimal> NetMaterialValueUnitary { get; set; }

    public Nullable<decimal> TotalListUnitary { get; set; }

    public Nullable<decimal> LCPackagePercentage { get; set; }

    public Nullable<decimal> LCPackageMultiplier { get; set; }

    public Nullable<decimal> CommissionAmountLCPackage { get; set; }

    public Nullable<decimal> NetMultiplierLCPackage { get; set; }

    public Nullable<decimal> NetMaterialValueLCPackage { get; set; }

    public Nullable<decimal> TotalListLCPackage { get; set; }



    public virtual CommissionCalculation CommissionCalculation1 { get; set; }

    public virtual CommissionCalculation CommissionCalculation2 { get; set; }

    public virtual CommissionRequest CommissionRequest { get; set; }

    public virtual Project Project { get; set; }

    public virtual Quote Quote { get; set; }

}

}
