
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class Country

{

    public Country()
    {

        this.States = new HashSet<State>();

    }


    public string CountryCode { get; set; }

    public string Name { get; set; }

    public string ISO3 { get; set; }

    public Nullable<int> PhoneCode { get; set; }



    public virtual ICollection<State> States { get; set; }

}

}
