
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class CustomerType

{

    public CustomerType()
    {

        this.CommissionRequests = new HashSet<CommissionRequest>();

    }


    public byte CustomerTypeId { get; set; }

    public string CustomerTypeDescription { get; set; }



    public virtual ICollection<CommissionRequest> CommissionRequests { get; set; }

}

}
