
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class DecisionTreeDependancy

{

    public int id { get; set; }

    public int ConfigId { get; set; }

    public int SystemIndex { get; set; }

    public int index { get; set; }

}

}
