
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class DiscountRequest
 : IConcurrency 
{

    public DiscountRequest()
    {

        this.Orders = new HashSet<Order>();

    }


    public long DiscountRequestId { get; set; }

    public long ProjectId { get; set; }

    public long QuoteId { get; set; }

    public decimal StartUpCosts { get; set; }

    public decimal RequestedDiscount { get; set; }

    public decimal RequestedCommission { get; set; }

    public System.DateTime RequestedOn { get; set; }

    public byte DiscountRequestStatusTypeId { get; set; }

    public System.DateTime StatusTypeModifiedOn { get; set; }

    public Nullable<long> StatusTypeModifiedBy { get; set; }

    public Nullable<byte> SystemBasisDesignTypeId { get; set; }

    public Nullable<byte> ZoneStrategyTypeId { get; set; }

    public Nullable<byte> BrandSpecifiedTypeId { get; set; }

    public Nullable<byte> BrandApprovedTypeId { get; set; }

    public bool HasCompetitorPrice { get; set; }

    public Nullable<decimal> CompetitorPrice { get; set; }

    public bool HasCompetitorQuote { get; set; }

    public string CompetitorQuoteFileName { get; set; }

    public bool HasCompetitorLineComparsion { get; set; }

    public string CompetitorLineComparsionFileName { get; set; }

    public bool IsConfidentCompetitorQuote { get; set; }

    public bool ApprovalAssuresOrder { get; set; }

    public Nullable<System.DateTime> OrderPlannedFor { get; set; }

    public Nullable<System.DateTime> OrderDeliveryDate { get; set; }

    public string Notes { get; set; }

    public string ResponseNotes { get; set; }

    public System.DateTime Timestamp { get; set; }

    public Nullable<byte> DaikinEquipmentAtAdvantageTypeId { get; set; }

    public Nullable<byte> ProbabilityOfCloseTypeId { get; set; }

    public Nullable<decimal> ApprovedDiscount { get; set; }

    public string EmailsList { get; set; }

    public decimal ApprovedDiscountSplit { get; set; }

    public decimal ApprovedDiscountVRV { get; set; }

    public decimal RequestedDiscountVRV { get; set; }

    public decimal RequestedDiscountSplit { get; set; }

    public Nullable<decimal> ApprovedDiscountUnitary { get; set; }

    public Nullable<decimal> RequestedDiscountUnitary { get; set; }

    public Nullable<decimal> ApprovedDiscountLCPackage { get; set; }

    public Nullable<decimal> RequestedDiscountLCPackage { get; set; }



    public virtual BrandCompetitorType BrandApprovedType { get; set; }

    public virtual BrandCompetitorType BrandSpecifiedType { get; set; }

    public virtual DiscountRequestStatusType DiscountRequestStatusType { get; set; }

    public virtual Quote Quote { get; set; }

    public virtual SystemBasisDesignType SystemBasisDesignType { get; set; }

    public virtual ZoneStrategyType ZoneStrategyType { get; set; }

    public virtual DaikinEquipmentAtAdvantageType DaikinEquipmentAtAdvantageType { get; set; }

    public virtual ProbablilityOfCloseType ProbablilityOfCloseType { get; set; }

    public virtual ICollection<Order> Orders { get; set; }

}

}
