
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class DocumentType

{

    public DocumentType()
    {

        this.Document = new HashSet<Document>();

    }


    public int DocumentTypeId { get; set; }

    public string Description { get; set; }

    public Nullable<short> Rank { get; set; }

    public string Name { get; set; }



    public virtual ICollection<Document> Document { get; set; }

}

}
