
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class Document
 : IConcurrency 
{

    public Document()
    {

        this.Products = new HashSet<DocumentProductLink>();

    }


    public System.Guid DocumentId { get; set; }

    public int DocumentTypeId { get; set; }

    public string FileName { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public System.DateTime ModifiedOn { get; set; }

    public System.DateTime Timestamp { get; set; }

    public string PIMDocumentId { get; set; }

    public Nullable<System.DateTime> PIMUploadDate { get; set; }

    public string FileExtension { get; set; }

    public string Name { get; set; }



    public virtual ICollection<DocumentProductLink> Products { get; set; }

    public virtual DocumentType DocumentType { get; set; }

}

}
