
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class GridSetting

{

    public int GridId { get; set; }

    public string GridName { get; set; }

    public Nullable<int> columns { get; set; }

    public Nullable<int> page { get; set; }

    public Nullable<int> pageSize { get; set; }

    public string sort { get; set; }

    public string filter { get; set; }

    public string groups { get; set; }

    public Nullable<long> UserId { get; set; }

}

}
