
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class LibraryDocumentRelationship

{

    public int Id { get; set; }

    public int LibraryDocumentId { get; set; }

    public int LibraryDirectoryId { get; set; }



    public virtual LibraryDirectory LibraryDirectory { get; set; }

    public virtual LibraryDocument LibraryDocument { get; set; }

}

}
