
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class LineItemOptionType

{

    public LineItemOptionType()
    {

        this.OrderItemOptions = new HashSet<OrderItemOption>();

        this.QuoteItemOptions = new HashSet<QuoteItemOption>();

    }


    public byte LineItemOptionTypeId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }



    public virtual ICollection<OrderItemOption> OrderItemOptions { get; set; }

    public virtual ICollection<QuoteItemOption> QuoteItemOptions { get; set; }

}

}
