
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class Link

{

    public long LinkId { get; set; }

    public string LinkCategory { get; set; }

    public string LinkUrl { get; set; }

    public string LinkName { get; set; }

    public int Order { get; set; }

    public bool Enabled { get; set; }

}

}
