
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class MultiplierCategoryType
 : IConcurrency 
{

    public MultiplierCategoryType()
    {

        this.CommissionMultipliers = new HashSet<CommissionMultiplier>();

    }


    public DPO.Common.MultiplierCategoryTypeEnum MultiplierCategoryTypeID { get; set; }

    public string Name { get; set; }

    public System.DateTime Timestamp { get; set; }



    public virtual ICollection<CommissionMultiplier> CommissionMultipliers { get; set; }

}

}
