
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class OrderItem
 : IConcurrency 
{

    public OrderItem()
    {

        this.OrderItemOptions = new HashSet<OrderItemOption>();

    }


    public long OrderItemId { get; set; }

    public long OrderId { get; set; }

    public int LineSequence { get; set; }

    public Nullable<long> ParentProductId { get; set; }

    public long ProductId { get; set; }

    public long AccountMultiplierId { get; set; }

    public string ParentProductNumber { get; set; }

    public string ProductNumber { get; set; }

    public decimal Quantity { get; set; }

    public decimal Multiplier { get; set; }

    public decimal ListPrice { get; set; }

    public decimal NetPrice { get; set; }

    public decimal DiscountPercentage { get; set; }

    public decimal ExtendedNetPrice { get; set; }

    public System.DateTime Timestamp { get; set; }

    public string CodeString { get; set; }

    public Nullable<byte> LineItemTypeId { get; set; }

    public string ConfigType { get; set; }



    public virtual AccountMultiplier AccountMultiplier { get; set; }

    public virtual LineItemType LineItemType { get; set; }

    public virtual ICollection<OrderItemOption> OrderItemOptions { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }

    public virtual Product Product1 { get; set; }

}

}
