
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class Order
 : IConcurrency 
{

    public Order()
    {

        this.OrderAttachments = new HashSet<OrderAttachment>();

        this.OrderItemOptions = new HashSet<OrderItemOption>();

        this.OrderItems = new HashSet<OrderItem>();

    }


    public long OrderId { get; set; }

    public long QuoteId { get; set; }

    public Nullable<long> DiscountRequestId { get; set; }

    public Nullable<long> CommissionRequestId { get; set; }

    public long BusinessId { get; set; }

    public long ShipToAddressId { get; set; }

    public byte PricingTypeId { get; set; }

    public Nullable<int> ERPPOKey { get; set; }

    public string ERPOrderNumber { get; set; }

    public Nullable<System.DateTime> ERPOrderDate { get; set; }

    public string ERPStatus { get; set; }

    public string ERPComment { get; set; }

    public string ERPInvoiceNumber { get; set; }

    public Nullable<System.DateTime> ERPInvoiceDate { get; set; }

    public Nullable<System.DateTime> ERPShipDate { get; set; }

    public string PONumber { get; set; }

    public decimal TotalDiscountPercent { get; set; }

    public string Comments { get; set; }

    public Nullable<System.DateTime> EstimatedReleaseDate { get; set; }

    public bool DeliveryAppointmentRequired { get; set; }

    public string DeliveryContactName { get; set; }

    public string DeliveryContactPhone { get; set; }

    public byte OrderStatusTypeId { get; set; }

    public long SubmittedByUserId { get; set; }

    public Nullable<System.DateTime> SubmitDate { get; set; }

    public long CreatedByUserId { get; set; }

    public long UpdatedByUserId { get; set; }

    public System.DateTime Timestamp { get; set; }

    public System.DateTime OrderReleaseDate { get; set; }

    public Nullable<int> ConfigOrderNumber { get; set; }

    public Nullable<byte> OrderType { get; set; }

    public string WebServiceImportStatus { get; set; }

    public Nullable<System.DateTime> ModifyOn { get; set; }



    public virtual Address Address { get; set; }

    public virtual Business Business { get; set; }

    public virtual CommissionRequest CommissionRequest { get; set; }

    public virtual DiscountRequest DiscountRequest { get; set; }

    public virtual ICollection<OrderAttachment> OrderAttachments { get; set; }

    public virtual ICollection<OrderItemOption> OrderItemOptions { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; }

    public virtual OrderStatusType OrderStatusType { get; set; }

    public virtual Quote Quote { get; set; }

    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

    public virtual User User2 { get; set; }

}

}
