
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class Permission

{

    public long PermissionId { get; set; }

    public Nullable<long> ParentPermissionId { get; set; }

    public long ObjectId { get; set; }

    public DPO.Common.PermissionTypeEnum PermissionTypeId { get; set; }

    public int ReferenceId { get; set; }

    public Nullable<DPO.Common.EntityEnum> ObjectEntityId { get; set; }

    public Nullable<DPO.Common.EntityEnum> ReferenceEntityId { get; set; }



    public virtual PermissionType PermissionType { get; set; }

}

}
