
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class PIMAttributeMap

{

    public PIMAttributeMap()
    {

        this.PIMAttributeValueMaps = new HashSet<PIMAttributeValueMap>();

    }


    public int PIMAttributeMapId { get; set; }

    public DPO.Common.PIMMapTypeEnum MapTypeId { get; set; }

    public string PIMAttributeId { get; set; }

    public string DaikinCityEntityName { get; set; }

    public string DaikinCityAttributeId { get; set; }

    public bool Disabled { get; set; }

    public string DefaultValue { get; set; }



    public virtual PIMMapType PIMMapType { get; set; }

    public virtual ICollection<PIMAttributeValueMap> PIMAttributeValueMaps { get; set; }

}

}
