
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class PIMListOfValuesMap

{

    public int PIMListOfValuesMapId { get; set; }

    public string PIMListOfValuesId { get; set; }

    public string DaikinCityEntityName { get; set; }

    public string DaikinCityNameField { get; set; }

    public bool Disabled { get; set; }

    public string DaikinCityIdField { get; set; }

    public bool HasDefaultOption { get; set; }

    public Nullable<int> DefaultOptionId { get; set; }

    public string DefaultOptionName { get; set; }

    public Nullable<bool> UpdateNameField { get; set; }

}

}
