
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class Product
 : IConcurrency 
{

    public Product()
    {

        this.Documents = new HashSet<DocumentProductLink>();

        this.OrderItemOptions = new HashSet<OrderItemOption>();

        this.OrderItemOptions1 = new HashSet<OrderItemOption>();

        this.OrderItems = new HashSet<OrderItem>();

        this.OrderItems1 = new HashSet<OrderItem>();

        this.ParentProductAccessories = new HashSet<ProductAccessory>();

        this.ProductAccessories = new HashSet<ProductAccessory>();

        this.ProductNotes = new HashSet<ProductNote>();

        this.ProductSpecifications = new HashSet<ProductSpecification>();

        this.QuoteItems = new HashSet<QuoteItem>();

        this.QuoteItemOptions = new HashSet<QuoteItemOption>();

        this.QuoteItemOptions1 = new HashSet<QuoteItemOption>();

    }


    public long ProductId { get; set; }

    public string ProductNumber { get; set; }

    public string Name { get; set; }

    public string ProductClassCode { get; set; }

    public int ProductFamilyId { get; set; }

    public int ProductCategoryId { get; set; }

    public int BrandId { get; set; }

    public int ProductMarketTypeId { get; set; }

    public int ProductModelTypeId { get; set; }

    public int SubmittalSheetTypeId { get; set; }

    public int ProductStatusId { get; set; }

    public bool AllowCommissionScheme { get; set; }

    public decimal ListPrice { get; set; }

    public System.DateTime ModifiedOn { get; set; }

    public Nullable<int> ProductPowerVoltageTypeId { get; set; }

    public Nullable<decimal> HeatingCapacityRated { get; set; }

    public Nullable<decimal> CoolingCapacityRated { get; set; }

    public Nullable<decimal> EERNonDucted { get; set; }

    public Nullable<decimal> IEERNonDucted { get; set; }

    public Nullable<decimal> SEERNonDucted { get; set; }

    public Nullable<decimal> COP47NonDucted { get; set; }

    public Nullable<decimal> HSPFNonDucted { get; set; }

    public Nullable<int> MultiplierTypeId { get; set; }

    public Nullable<int> PriceClassCodeId { get; set; }

    public Nullable<int> UnitInstallationTypeId { get; set; }

    public Nullable<int> ProductCompressorStageId { get; set; }

    public Nullable<int> ProductGasValveTypeId { get; set; }

    public Nullable<int> ProductMotorSpeedTypeId { get; set; }

    public Nullable<int> ProductInstallationConfigurationTypeId { get; set; }

    public Nullable<int> ProductHeatExchangerTypeId { get; set; }

    public Nullable<int> ProductTypeId { get; set; }

    public Nullable<decimal> CoolingCapacityNominal { get; set; }

    public Nullable<decimal> AirFlowRateHighCooling { get; set; }

    public Nullable<decimal> AirFlowRateHighHeating { get; set; }

    public Nullable<int> ProductSubFamilyId { get; set; }

    public Nullable<int> ProductFunctionCategoryId { get; set; }

    public Nullable<int> ProductAccessoryTypeId { get; set; }

    public Nullable<int> ProductClassPIMId { get; set; }

    public Nullable<int> ProductEnergySourceTypeId { get; set; }

    public Nullable<decimal> Tonnage { get; set; }

    public System.DateTime Timestamp { get; set; }

    public Nullable<int> InventoryStatusId { get; set; }

    public Nullable<System.DateTime> InvAvailableDate { get; set; }



    public virtual Brand Brand { get; set; }

    public virtual ICollection<DocumentProductLink> Documents { get; set; }

    public virtual InventoryStatus InventoryStatuses { get; set; }

    public virtual MultiplierType MultiplierType { get; set; }

    public virtual ICollection<OrderItemOption> OrderItemOptions { get; set; }

    public virtual ICollection<OrderItemOption> OrderItemOptions1 { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; }

    public virtual ICollection<OrderItem> OrderItems1 { get; set; }

    public virtual ICollection<ProductAccessory> ParentProductAccessories { get; set; }

    public virtual ICollection<ProductAccessory> ProductAccessories { get; set; }

    public virtual ProductAccessoryType ProductAccessoryType { get; set; }

    public virtual ProductCategory ProductCategory { get; set; }

    public virtual ProductClassPIM ProductClassPIM { get; set; }

    public virtual ProductCompressorStage ProductCompressorStage { get; set; }

    public virtual ProductEnergySourceType ProductEnergySourceType { get; set; }

    public virtual ProductFamily ProductFamily { get; set; }

    public virtual ProductFunctionCategory ProductFunctionCategory { get; set; }

    public virtual ProductGasValveType ProductGasValveType { get; set; }

    public virtual ProductHeatExchangerType ProductHeatExchangerType { get; set; }

    public virtual ProductInstallationConfigurationType ProductInstallationConfigurationType { get; set; }

    public virtual ProductMarketType ProductMarket { get; set; }

    public virtual ProductModelType ProductModel { get; set; }

    public virtual ProductMotorSpeedType ProductMotorSpeedType { get; set; }

    public virtual ICollection<ProductNote> ProductNotes { get; set; }

    public virtual ProductPowerVoltageType ProductPowerVoltageType { get; set; }

    public virtual SubmittalSheetType SubmittialSheet { get; set; }

    public virtual ProductStatus ProductStatus { get; set; }

    public virtual ProductSubFamily ProductSubFamily { get; set; }

    public virtual ProductType ProductType { get; set; }

    public virtual UnitInstallationType UnitInstallationType { get; set; }

    public virtual ICollection<ProductSpecification> ProductSpecifications { get; set; }

    public virtual ICollection<QuoteItem> QuoteItems { get; set; }

    public virtual ICollection<QuoteItemOption> QuoteItemOptions { get; set; }

    public virtual ICollection<QuoteItemOption> QuoteItemOptions1 { get; set; }

}

}
