
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class ProductsWithNoMultiplier

{

    public int Id { get; set; }

    public long ProductId { get; set; }

    public string ProductNumber { get; set; }

    public string ProductClassCode { get; set; }

    public int ProductFamilyId { get; set; }

    public int ProductCategoryId { get; set; }

    public int ProductMarketTypeId { get; set; }

    public Nullable<int> MultiplierTypeId { get; set; }

    public Nullable<decimal> ListPrice { get; set; }

    public Nullable<int> PriceClassCodeId { get; set; }

    public System.DateTime ModifiedOn { get; set; }

    public byte[] TimeStamp { get; set; }

    public string Status { get; set; }

}

}
