
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class ProductStatus
 : IConcurrency 
{

    public ProductStatus()
    {

        this.Products = new HashSet<Product>();

    }


    public int ProductStatusId { get; set; }

    public string Description { get; set; }

    public System.DateTime Timestamp { get; set; }



    public virtual ProductStatus ProductStatuses1 { get; set; }

    public virtual ProductStatus ProductStatus1 { get; set; }

    public virtual ICollection<Product> Products { get; set; }

}

}
