
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class ProductSpecificationLabel

{

    public ProductSpecificationLabel()
    {

        this.ProductSpecifications = new HashSet<ProductSpecification>();

        this.ProductSpecificationKeyLookups = new HashSet<ProductSpecificationKeyLookup>();

    }


    public short ProductSpecificationLabelId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }



    public virtual ICollection<ProductSpecification> ProductSpecifications { get; set; }

    public virtual ICollection<ProductSpecificationKeyLookup> ProductSpecificationKeyLookups { get; set; }

}

}
