
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class ProductSpecificationKeyLookup

{

    public short ProductSpecificationLabelId { get; set; }

    public string Key { get; set; }

    public string Value { get; set; }



    public virtual ProductSpecificationLabel ProductSpecificationKeyLookups { get; set; }

}

}
