
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class ProjectPipelineNoteType
 : IConcurrency 
{

    public ProjectPipelineNoteType()
    {

        this.ProjectPipelineNotes = new HashSet<ProjectPipelineNote>();

    }


    public byte ProjectPipelineNoteTypeId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public System.DateTime Timestamp { get; set; }



    public virtual ICollection<ProjectPipelineNote> ProjectPipelineNotes { get; set; }

}

}
