
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class ProjectPipelineNote
 : IConcurrency 
{

    public long ProjectPipelineNoteId { get; set; }

    public byte ProjectPipelineNoteTypeId { get; set; }

    public long ProjectId { get; set; }

    public string Title { get; set; }

    public string Note { get; set; }

    public System.DateTime Timestamp { get; set; }

    public long OwnerId { get; set; }



    public virtual ProjectPipelineNoteType ProjectPipelineNoteType { get; set; }

    public virtual Project Project { get; set; }

    public virtual User User { get; set; }

}

}
