
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class Project
 : IConcurrency 
{

    public Project()
    {

        this.ProjectTransfers = new HashSet<ProjectTransfer>();

        this.Quotes = new HashSet<Quote>();

        this.ProjectPipelineNotes = new HashSet<ProjectPipelineNote>();

        this.CommissionCalculations = new HashSet<CommissionCalculation>();

        this.CommissionRequests = new HashSet<CommissionRequest>();

    }


    public long ProjectId { get; set; }

    public long OwnerId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string CustomerName { get; set; }

    public string EngineerName { get; set; }

    public string DealerContractorName { get; set; }

    public string SellerName { get; set; }

    public string ShipToName { get; set; }

    public System.DateTime ProjectDate { get; set; }

    public System.DateTime BidDate { get; set; }

    public System.DateTime EstimatedClose { get; set; }

    public System.DateTime EstimatedDelivery { get; set; }

    public System.DateTime Expiration { get; set; }

    public byte ProjectOpenStatusTypeId { get; set; }

    public byte ConstructionTypeId { get; set; }

    public byte ProjectTypeId { get; set; }

    public DPO.Common.ProjectStatusTypeEnum ProjectStatusTypeId { get; set; }

    public byte VerticalMarketTypeId { get; set; }

    public Nullable<long> EngineerAddressId { get; set; }

    public Nullable<long> SellerAddressId { get; set; }

    public Nullable<long> CustomerAddressId { get; set; }

    public Nullable<long> ShipToAddressId { get; set; }

    public int ActiveVersion { get; set; }

    public bool Deleted { get; set; }

    public System.DateTime Timestamp { get; set; }

    public string ProjectStatusNotes { get; set; }

    public DPO.Common.ProjectLeadStatusTypeEnum ProjectLeadStatusTypeId { get; set; }

    public string EngineerBusinessName { get; set; }

    public string ERPFirstOrderNumber { get; set; }

    public Nullable<System.DateTime> ERPFirstOrderDate { get; set; }

    public string ERPFirstOrderComment { get; set; }

    public string ERPFirstInvoiceNumber { get; set; }

    public Nullable<System.DateTime> ERPFirstInvoiceDate { get; set; }

    public Nullable<int> ERPFirstInvoiceSequence { get; set; }

    public Nullable<System.DateTime> ERPFirstShipDate { get; set; }

    public string ERPFirstPONumber { get; set; }

    public string DealerContractorBusinessName { get; set; }

    public Nullable<int> SquareFootage { get; set; }

    public Nullable<int> NumberOfFloors { get; set; }

    public Nullable<int> OrderStatus { get; set; }

    public Nullable<System.DateTime> ActualCloseDate { get; set; }

    public Nullable<System.DateTime> EstimateReleaseDate { get; set; }

    public Nullable<System.DateTime> ActualDeliveryDate { get; set; }

    public string WebServiceImportStatus { get; set; }

    public Nullable<long> ModifyBy { get; set; }

    public Nullable<System.DateTime> ModifyOn { get; set; }



    public virtual Address CustomerAddress { get; set; }

    public virtual Address EngineerAddress { get; set; }

    public virtual Address SellerAddress { get; set; }

    public virtual Address ShipToAddress { get; set; }

    public virtual ConstructionType ConstructionType { get; set; }

    public virtual ProjectStatusType ProjectStatusType { get; set; }

    public virtual ProjectType ProjectType { get; set; }

    public virtual VerticalMarketType VerticalMarketType { get; set; }

    public virtual ICollection<ProjectTransfer> ProjectTransfers { get; set; }

    public virtual ProjectOpenStatusType ProjectOpenStatusType { get; set; }

    public virtual ICollection<Quote> Quotes { get; set; }

    public virtual User Owner { get; set; }

    public virtual ProjectLeadStatusType ProjectLeadStatusType { get; set; }

    public virtual ICollection<ProjectPipelineNote> ProjectPipelineNotes { get; set; }

    public virtual ICollection<CommissionCalculation> CommissionCalculations { get; set; }

    public virtual ICollection<CommissionRequest> CommissionRequests { get; set; }

}

}
