
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class QuoteItem
 : IConcurrency 
{

    public QuoteItem()
    {

        this.QuoteItemOptions = new HashSet<QuoteItemOption>();

    }


    public long QuoteItemId { get; set; }

    public long QuoteId { get; set; }

    public Nullable<long> ProductId { get; set; }

    public string ProductNumber { get; set; }

    public string Description { get; set; }

    public decimal Quantity { get; set; }

    public decimal ListPrice { get; set; }

    public decimal Multiplier { get; set; }

    public Nullable<long> AccountMultiplierId { get; set; }

    public System.DateTime Timestamp { get; set; }

    public string Tags { get; set; }

    public string CodeString { get; set; }

    public Nullable<byte> LineItemTypeId { get; set; }

    public string ConfigType { get; set; }



    public virtual AccountMultiplier AccountMultiplier { get; set; }

    public virtual Quote Quote { get; set; }

    public virtual LineItemType LineItemType { get; set; }

    public virtual ICollection<QuoteItemOption> QuoteItemOptions { get; set; }

    public virtual Product Product { get; set; }

}

}
