
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class Seed

{

    public int SeedId { get; set; }

    public int SeedTypeId { get; set; }

    public string SeedName { get; set; }

    public int SeedNumber { get; set; }

    public int Step { get; set; }



    public virtual SeedType SeedType { get; set; }

}

}
