
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class SeedType

{

    public SeedType()
    {

        this.Seeds = new HashSet<Seed>();

    }


    public int SeedTypeId { get; set; }

    public string SeedTypeName { get; set; }



    public virtual ICollection<Seed> Seeds { get; set; }

}

}
