
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class UnitaryCommissionCurve
 : IConcurrency 
{

    public int CommissionCurveId { get; set; }

    public int MultiplierCategoryTypeId { get; set; }

    public decimal Multiplier { get; set; }

    public decimal CommissionPercentage_AH { get; set; }

    public decimal CommissionPercentage_CN { get; set; }

    public System.DateTime Timestamp { get; set; }

}

}
