
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class User
 : IConcurrency 
{

    public User()
    {

        this.Projects = new HashSet<Project>();

        this.ProjectTransfers = new HashSet<ProjectTransfer>();

        this.UserBasketItems = new HashSet<UserBasketItem>();

        this.ProjectPipelineNotes = new HashSet<ProjectPipelineNote>();

        this.Orders = new HashSet<Order>();

        this.Orders1 = new HashSet<Order>();

        this.Orders2 = new HashSet<Order>();

    }


    public long UserId { get; set; }

    public long GroupId { get; set; }

    public Nullable<bool> IsGroupOwner { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public int Salt { get; set; }

    public DPO.Common.UserTypeEnum UserTypeId { get; set; }

    public bool UseBusinessAddress { get; set; }

    public Nullable<long> BusinessId { get; set; }

    public Nullable<long> AddressId { get; set; }

    public Nullable<long> ContactId { get; set; }

    public bool Approved { get; set; }

    public bool Rejected { get; set; }

    public bool Enabled { get; set; }

    public Nullable<System.DateTime> RegisteredOn { get; set; }

    public Nullable<System.DateTime> ApprovedOn { get; set; }

    public bool ShowPricing { get; set; }

    public Nullable<System.DateTime> LastLoginOn { get; set; }

    public string DisplaySettings { get; set; }

    public System.DateTime Timestamp { get; set; }

    public string DPOwebVersion { get; set; }

    public Nullable<long> ModifyBy { get; set; }

    public Nullable<System.DateTime> ModifyOn { get; set; }



    public virtual Address Address { get; set; }

    public virtual Business Business { get; set; }

    public virtual Contact Contact { get; set; }

    public virtual Group Group { get; set; }

    public virtual ICollection<Project> Projects { get; set; }

    public virtual ICollection<ProjectTransfer> ProjectTransfers { get; set; }

    public virtual ICollection<UserBasketItem> UserBasketItems { get; set; }

    public virtual UserType UserType { get; set; }

    public virtual ICollection<ProjectPipelineNote> ProjectPipelineNotes { get; set; }

    public virtual ICollection<Order> Orders { get; set; }

    public virtual ICollection<Order> Orders1 { get; set; }

    public virtual ICollection<Order> Orders2 { get; set; }

}

}
