
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class VwProductDocument
 : IConcurrency 
{

    public long ProductId { get; set; }

    public System.Guid DocumentId { get; set; }

    public int DocumentTypeId { get; set; }

    public string DocumentTypeDescription { get; set; }

    public string FileName { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public System.DateTime ModifiedOn { get; set; }

    public System.DateTime Timestamp { get; set; }

    public Nullable<short> Rank { get; set; }

    public string Name { get; set; }

}

}
