
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class VwProductSpecification

{

    public long ProductId { get; set; }

    public short SpecificationId { get; set; }

    public string SpecificationName { get; set; }

    public string Value { get; set; }

    public string SpecificationKey { get; set; }

}

}
