//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DPO.Resources.Common.DataMessages", typeof(DataMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update user. User record passed was empty or user id was empty..
        /// </summary>
        public static string DM002 {
            get {
                return ResourceManager.GetString("DM002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record you attempted to edit has just been modified by another user. To prevent changes being over written your edit operation was cancelled. Please refresh the screen and try again..
        /// </summary>
        public static string DM003 {
            get {
                return ResourceManager.GetString("DM003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not accessible..
        /// </summary>
        public static string DM004 {
            get {
                return ResourceManager.GetString("DM004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your access level doesnt not allow for this operation..
        /// </summary>
        public static string DM005 {
            get {
                return ResourceManager.GetString("DM005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business is not accessible..
        /// </summary>
        public static string DM006 {
            get {
                return ResourceManager.GetString("DM006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project  is not accessible..
        /// </summary>
        public static string DM007 {
            get {
                return ResourceManager.GetString("DM007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner has an an invalid value. This internal error was raise to prevent an ownerless project from being created. Contact systems support..
        /// </summary>
        public static string DM008 {
            get {
                return ResourceManager.GetString("DM008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project needs to be assigned to a customer.
        /// </summary>
        public static string DM009 {
            get {
                return ResourceManager.GetString("DM009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote not accessible..
        /// </summary>
        public static string DM010 {
            get {
                return ResourceManager.GetString("DM010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote can only be added through an exisiting project..
        /// </summary>
        public static string DM011 {
            get {
                return ResourceManager.GetString("DM011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote needs to be part of a project..
        /// </summary>
        public static string DM012 {
            get {
                return ResourceManager.GetString("DM012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a state..
        /// </summary>
        public static string DM016 {
            get {
                return ResourceManager.GetString("DM016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a country..
        /// </summary>
        public static string DM018 {
            get {
                return ResourceManager.GetString("DM018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact number required..
        /// </summary>
        public static string DM019 {
            get {
                return ResourceManager.GetString("DM019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been updated..
        /// </summary>
        public static string DM020 {
            get {
                return ResourceManager.GetString("DM020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been added..
        /// </summary>
        public static string DM021 {
            get {
                return ResourceManager.GetString("DM021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been deleted..
        /// </summary>
        public static string DM022 {
            get {
                return ResourceManager.GetString("DM022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote Item not accessible..
        /// </summary>
        public static string DM023 {
            get {
                return ResourceManager.GetString("DM023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address not accessible..
        /// </summary>
        public static string DM024 {
            get {
                return ResourceManager.GetString("DM024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact not accessible..
        /// </summary>
        public static string DM025 {
            get {
                return ResourceManager.GetString("DM025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem actioning the request..
        /// </summary>
        public static string DM026 {
            get {
                return ResourceManager.GetString("DM026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Group Id: {0} could not be loaded. Required for group setting..
        /// </summary>
        public static string DM027 {
            get {
                return ResourceManager.GetString("DM027", resourceCulture);
            }
        }
    }
}
