//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SystemMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DPO.Resources.Common.SystemMessages", typeof(SystemMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection string name of &apos;{0}&apos; was not found in the config file..
        /// </summary>
        public static string SM001 {
            get {
                return ResourceManager.GetString("SM001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but an application error has occurred. Please contact support and explain exactly the process which led to this error..
        /// </summary>
        public static string SM002 {
            get {
                return ResourceManager.GetString("SM002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem generating a security key. Please try again later or contact customer services..
        /// </summary>
        public static string SM003 {
            get {
                return ResourceManager.GetString("SM003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem sending the email..
        /// </summary>
        public static string SM004 {
            get {
                return ResourceManager.GetString("SM004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent..
        /// </summary>
        public static string SM005 {
            get {
                return ResourceManager.GetString("SM005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database update failed, please try again..
        /// </summary>
        public static string SM006 {
            get {
                return ResourceManager.GetString("SM006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security has prevented the update from taking place. Please contact customer services..
        /// </summary>
        public static string SM007 {
            get {
                return ResourceManager.GetString("SM007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of file being uploaded is not allowed..
        /// </summary>
        public static string SM008 {
            get {
                return ResourceManager.GetString("SM008", resourceCulture);
            }
        }
    }
}
