//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPO.Domain.DataQualityService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://goodmanmfg.com/GMC/WebService/Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DPO.Domain.DataQualityService.DataQualityRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DPO.Domain.DataQualityService.SoundexRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DPO.Domain.DataQualityService.MetaphoneCompareRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DPO.Domain.DataQualityService.CleanAddressMultipleRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DPO.Domain.DataQualityService.CleanAddressRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DPO.Domain.DataQualityService.MetaphoneRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DPO.Domain.DataQualityService.CleanPhoneRequest))]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataQualityRequest", Namespace="http://goodmanmfg.com/GMC/WebService/DataQualityService/Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DPO.Domain.DataQualityService.SoundexRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DPO.Domain.DataQualityService.MetaphoneCompareRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DPO.Domain.DataQualityService.CleanAddressMultipleRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DPO.Domain.DataQualityService.CleanAddressRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DPO.Domain.DataQualityService.MetaphoneRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DPO.Domain.DataQualityService.CleanPhoneRequest))]
    public partial class DataQualityRequest : DPO.Domain.DataQualityService.Request {
        
        private string TokenIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TokenId {
            get {
                return this.TokenIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenIdField, value) != true)) {
                    this.TokenIdField = value;
                    this.RaisePropertyChanged("TokenId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoundexRequest", Namespace="http://goodmanmfg.com/GMC/WebService/DataQualityService/Entities")]
    [System.SerializableAttribute()]
    public partial class SoundexRequest : DPO.Domain.DataQualityService.DataQualityRequest {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MetaphoneCompareRequest", Namespace="http://goodmanmfg.com/GMC/WebService/DataQualityService/Entities")]
    [System.SerializableAttribute()]
    public partial class MetaphoneCompareRequest : DPO.Domain.DataQualityService.DataQualityRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Compare1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Compare2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DPO.Domain.DataQualityService.MetaphoneType TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Compare1 {
            get {
                return this.Compare1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Compare1Field, value) != true)) {
                    this.Compare1Field = value;
                    this.RaisePropertyChanged("Compare1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Compare2 {
            get {
                return this.Compare2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Compare2Field, value) != true)) {
                    this.Compare2Field = value;
                    this.RaisePropertyChanged("Compare2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DPO.Domain.DataQualityService.MetaphoneType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CleanAddressMultipleRequest", Namespace="http://goodmanmfg.com/GMC/WebService/DataQualityService/Entities")]
    [System.SerializableAttribute()]
    public partial class CleanAddressMultipleRequest : DPO.Domain.DataQualityService.DataQualityRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DPO.Domain.DataQualityService.DQAddress[] AddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumSuggestionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DPO.Domain.DataQualityService.DQAddress[] Addresses {
            get {
                return this.AddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressesField, value) != true)) {
                    this.AddressesField = value;
                    this.RaisePropertyChanged("Addresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTest {
            get {
                return this.IsTestField;
            }
            set {
                if ((this.IsTestField.Equals(value) != true)) {
                    this.IsTestField = value;
                    this.RaisePropertyChanged("IsTest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumSuggestions {
            get {
                return this.NumSuggestionsField;
            }
            set {
                if ((this.NumSuggestionsField.Equals(value) != true)) {
                    this.NumSuggestionsField = value;
                    this.RaisePropertyChanged("NumSuggestions");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CleanAddressRequest", Namespace="http://goodmanmfg.com/GMC/WebService/DataQualityService/Entities")]
    [System.SerializableAttribute()]
    public partial class CleanAddressRequest : DPO.Domain.DataQualityService.DataQualityRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DPO.Domain.DataQualityService.DQAddress AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumSuggestionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DPO.Domain.DataQualityService.DQAddress Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTest {
            get {
                return this.IsTestField;
            }
            set {
                if ((this.IsTestField.Equals(value) != true)) {
                    this.IsTestField = value;
                    this.RaisePropertyChanged("IsTest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumSuggestions {
            get {
                return this.NumSuggestionsField;
            }
            set {
                if ((this.NumSuggestionsField.Equals(value) != true)) {
                    this.NumSuggestionsField = value;
                    this.RaisePropertyChanged("NumSuggestions");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MetaphoneRequest", Namespace="http://goodmanmfg.com/GMC/WebService/DataQualityService/Entities")]
    [System.SerializableAttribute()]
    public partial class MetaphoneRequest : DPO.Domain.DataQualityService.DataQualityRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DPO.Domain.DataQualityService.MetaphoneType TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DPO.Domain.DataQualityService.MetaphoneType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CleanPhoneRequest", Namespace="http://goodmanmfg.com/GMC/WebService/DataQualityService/Entities")]
    [System.SerializableAttribute()]
    public partial class CleanPhoneRequest : DPO.Domain.DataQualityService.DataQualityRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MetaphoneType", Namespace="http://goodmanmfg.com/GMC/WebService/DataQualityService/Entities")]
    public enum MetaphoneType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Metaphone = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DoubleMetaphone = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DQAddress", Namespace="http://goodmanmfg.com/GMC/WebService/DataQualityService/Entities")]
    [System.SerializableAttribute()]
    public partial class DQAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddresseeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityStateZipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyFipsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DpvConfirmCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrbanizationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Zip4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Zip5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LongitudeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Addressee {
            get {
                return this.AddresseeField;
            }
            set {
                if ((object.ReferenceEquals(this.AddresseeField, value) != true)) {
                    this.AddresseeField = value;
                    this.RaisePropertyChanged("Addressee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Barcode {
            get {
                return this.BarcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BarcodeField, value) != true)) {
                    this.BarcodeField = value;
                    this.RaisePropertyChanged("Barcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityStateZip {
            get {
                return this.CityStateZipField;
            }
            set {
                if ((object.ReferenceEquals(this.CityStateZipField, value) != true)) {
                    this.CityStateZipField = value;
                    this.RaisePropertyChanged("CityStateZip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountyFips {
            get {
                return this.CountyFipsField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyFipsField, value) != true)) {
                    this.CountyFipsField = value;
                    this.RaisePropertyChanged("CountyFips");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DpvConfirmCode {
            get {
                return this.DpvConfirmCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DpvConfirmCodeField, value) != true)) {
                    this.DpvConfirmCodeField = value;
                    this.RaisePropertyChanged("DpvConfirmCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line1 {
            get {
                return this.Line1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line1Field, value) != true)) {
                    this.Line1Field = value;
                    this.RaisePropertyChanged("Line1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line2 {
            get {
                return this.Line2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line2Field, value) != true)) {
                    this.Line2Field = value;
                    this.RaisePropertyChanged("Line2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line3 {
            get {
                return this.Line3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line3Field, value) != true)) {
                    this.Line3Field = value;
                    this.RaisePropertyChanged("Line3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line4 {
            get {
                return this.Line4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line4Field, value) != true)) {
                    this.Line4Field = value;
                    this.RaisePropertyChanged("Line4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateProvince {
            get {
                return this.StateProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.StateProvinceField, value) != true)) {
                    this.StateProvinceField = value;
                    this.RaisePropertyChanged("StateProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitNumber {
            get {
                return this.UnitNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitNumberField, value) != true)) {
                    this.UnitNumberField = value;
                    this.RaisePropertyChanged("UnitNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Urbanization {
            get {
                return this.UrbanizationField;
            }
            set {
                if ((object.ReferenceEquals(this.UrbanizationField, value) != true)) {
                    this.UrbanizationField = value;
                    this.RaisePropertyChanged("Urbanization");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip4 {
            get {
                return this.Zip4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Zip4Field, value) != true)) {
                    this.Zip4Field = value;
                    this.RaisePropertyChanged("Zip4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip5 {
            get {
                return this.Zip5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Zip5Field, value) != true)) {
                    this.Zip5Field = value;
                    this.RaisePropertyChanged("Zip5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public decimal Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public decimal Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://goodmanmfg.com/GMC/WebService/Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DPO.Domain.DataQualityService.DataQualityResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DPO.Domain.DataQualityService.MetaphoneResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DPO.Domain.DataQualityService.CleanAddressResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DPO.Domain.DataQualityService.CleanAddressMultipleResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DPO.Domain.DataQualityService.MetaphoneCompareResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DPO.Domain.DataQualityService.CleanPhoneResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DPO.Domain.DataQualityService.SoundexResponse))]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DPO.Domain.DataQualityService.Error ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DPO.Domain.DataQualityService.Error Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://goodmanmfg.com/GMC/WebService/Entities")]
    [System.SerializableAttribute()]
    public partial class Error : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DPO.Domain.DataQualityService.SeverityLevel SeverityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeverityCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DPO.Domain.DataQualityService.SeverityLevel Severity {
            get {
                return this.SeverityField;
            }
            set {
                if ((this.SeverityField.Equals(value) != true)) {
                    this.SeverityField = value;
                    this.RaisePropertyChanged("Severity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int SeverityCode {
            get {
                return this.SeverityCodeField;
            }
            set {
                if ((this.SeverityCodeField.Equals(value) != true)) {
                    this.SeverityCodeField = value;
                    this.RaisePropertyChanged("SeverityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int CategoryCode {
            get {
                return this.CategoryCodeField;
            }
            set {
                if ((this.CategoryCodeField.Equals(value) != true)) {
                    this.CategoryCodeField = value;
                    this.RaisePropertyChanged("CategoryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataQualityResponse", Namespace="http://goodmanmfg.com/GMC/WebService/DataQualityService/Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DPO.Domain.DataQualityService.MetaphoneResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DPO.Domain.DataQualityService.CleanAddressResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DPO.Domain.DataQualityService.CleanAddressMultipleResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DPO.Domain.DataQualityService.MetaphoneCompareResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DPO.Domain.DataQualityService.CleanPhoneResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DPO.Domain.DataQualityService.SoundexResponse))]
    public partial class DataQualityResponse : DPO.Domain.DataQualityService.Response {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MetaphoneResponse", Namespace="http://goodmanmfg.com/GMC/WebService/DataQualityService/Entities")]
    [System.SerializableAttribute()]
    public partial class MetaphoneResponse : DPO.Domain.DataQualityService.DataQualityResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DPO.Domain.DataQualityService.MetaphoneResult ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DPO.Domain.DataQualityService.MetaphoneResult Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CleanAddressResponse", Namespace="http://goodmanmfg.com/GMC/WebService/DataQualityService/Entities")]
    [System.SerializableAttribute()]
    public partial class CleanAddressResponse : DPO.Domain.DataQualityService.DataQualityResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DPO.Domain.DataQualityService.DQAddress[] AddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAddressValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsZipStateValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsZipValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumSuggestionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DPO.Domain.DataQualityService.DQAddress[] Addresses {
            get {
                return this.AddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressesField, value) != true)) {
                    this.AddressesField = value;
                    this.RaisePropertyChanged("Addresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAddressValid {
            get {
                return this.IsAddressValidField;
            }
            set {
                if ((this.IsAddressValidField.Equals(value) != true)) {
                    this.IsAddressValidField = value;
                    this.RaisePropertyChanged("IsAddressValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsZipStateValid {
            get {
                return this.IsZipStateValidField;
            }
            set {
                if ((this.IsZipStateValidField.Equals(value) != true)) {
                    this.IsZipStateValidField = value;
                    this.RaisePropertyChanged("IsZipStateValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsZipValid {
            get {
                return this.IsZipValidField;
            }
            set {
                if ((this.IsZipValidField.Equals(value) != true)) {
                    this.IsZipValidField = value;
                    this.RaisePropertyChanged("IsZipValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumSuggestions {
            get {
                return this.NumSuggestionsField;
            }
            set {
                if ((this.NumSuggestionsField.Equals(value) != true)) {
                    this.NumSuggestionsField = value;
                    this.RaisePropertyChanged("NumSuggestions");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CleanAddressMultipleResponse", Namespace="http://goodmanmfg.com/GMC/WebService/DataQualityService/Entities")]
    [System.SerializableAttribute()]
    public partial class CleanAddressMultipleResponse : DPO.Domain.DataQualityService.DataQualityResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DPO.Domain.DataQualityService.DQAddress[][] AddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumSuggestionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DPO.Domain.DataQualityService.DQAddress[][] Addresses {
            get {
                return this.AddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressesField, value) != true)) {
                    this.AddressesField = value;
                    this.RaisePropertyChanged("Addresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumSuggestions {
            get {
                return this.NumSuggestionsField;
            }
            set {
                if ((this.NumSuggestionsField.Equals(value) != true)) {
                    this.NumSuggestionsField = value;
                    this.RaisePropertyChanged("NumSuggestions");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MetaphoneCompareResponse", Namespace="http://goodmanmfg.com/GMC/WebService/DataQualityService/Entities")]
    [System.SerializableAttribute()]
    public partial class MetaphoneCompareResponse : DPO.Domain.DataQualityService.DataQualityResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DPO.Domain.DataQualityService.MetaphoneResult Result1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DPO.Domain.DataQualityService.MetaphoneResult Result2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DPO.Domain.DataQualityService.MetaphoneMatchStrength StrengthField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DPO.Domain.DataQualityService.MetaphoneResult Result1 {
            get {
                return this.Result1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Result1Field, value) != true)) {
                    this.Result1Field = value;
                    this.RaisePropertyChanged("Result1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DPO.Domain.DataQualityService.MetaphoneResult Result2 {
            get {
                return this.Result2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Result2Field, value) != true)) {
                    this.Result2Field = value;
                    this.RaisePropertyChanged("Result2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DPO.Domain.DataQualityService.MetaphoneMatchStrength Strength {
            get {
                return this.StrengthField;
            }
            set {
                if ((this.StrengthField.Equals(value) != true)) {
                    this.StrengthField = value;
                    this.RaisePropertyChanged("Strength");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CleanPhoneResponse", Namespace="http://goodmanmfg.com/GMC/WebService/DataQualityService/Entities")]
    [System.SerializableAttribute()]
    public partial class CleanPhoneResponse : DPO.Domain.DataQualityService.DataQualityResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DPO.Domain.DataQualityService.DQPhoneNumber PhoneNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DPO.Domain.DataQualityService.DQPhoneNumber PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoundexResponse", Namespace="http://goodmanmfg.com/GMC/WebService/DataQualityService/Entities")]
    [System.SerializableAttribute()]
    public partial class SoundexResponse : DPO.Domain.DataQualityService.DataQualityResponse {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeverityLevel", Namespace="http://goodmanmfg.com/GMC/WebService/Entities")]
    public enum SeverityLevel : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Information = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exception = 20,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MetaphoneResult", Namespace="http://goodmanmfg.com/GMC/WebService/DataQualityService/Entities")]
    [System.SerializableAttribute()]
    public partial class MetaphoneResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlternateKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort AlternateKeyShortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort PrimaryKeyShortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlternateKey {
            get {
                return this.AlternateKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.AlternateKeyField, value) != true)) {
                    this.AlternateKeyField = value;
                    this.RaisePropertyChanged("AlternateKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort AlternateKeyShort {
            get {
                return this.AlternateKeyShortField;
            }
            set {
                if ((this.AlternateKeyShortField.Equals(value) != true)) {
                    this.AlternateKeyShortField = value;
                    this.RaisePropertyChanged("AlternateKeyShort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryKey {
            get {
                return this.PrimaryKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryKeyField, value) != true)) {
                    this.PrimaryKeyField = value;
                    this.RaisePropertyChanged("PrimaryKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort PrimaryKeyShort {
            get {
                return this.PrimaryKeyShortField;
            }
            set {
                if ((this.PrimaryKeyShortField.Equals(value) != true)) {
                    this.PrimaryKeyShortField = value;
                    this.RaisePropertyChanged("PrimaryKeyShort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MetaphoneMatchStrength", Namespace="http://goodmanmfg.com/GMC/WebService/DataQualityService/Entities")]
    public enum MetaphoneMatchStrength : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Low = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Medium = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        High = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DQPhoneNumber", Namespace="http://goodmanmfg.com/GMC/WebService/DataQualityService/Entities")]
    [System.SerializableAttribute()]
    public partial class DQPhoneNumber : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LineNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrefixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateOrProvinceTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreaCode {
            get {
                return this.AreaCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaCodeField, value) != true)) {
                    this.AreaCodeField = value;
                    this.RaisePropertyChanged("AreaCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryText {
            get {
                return this.CountryTextField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryTextField, value) != true)) {
                    this.CountryTextField = value;
                    this.RaisePropertyChanged("CountryText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionField, value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LineNumber {
            get {
                return this.LineNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.LineNumberField, value) != true)) {
                    this.LineNumberField = value;
                    this.RaisePropertyChanged("LineNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefix {
            get {
                return this.PrefixField;
            }
            set {
                if ((object.ReferenceEquals(this.PrefixField, value) != true)) {
                    this.PrefixField = value;
                    this.RaisePropertyChanged("Prefix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateOrProvinceText {
            get {
                return this.StateOrProvinceTextField;
            }
            set {
                if ((object.ReferenceEquals(this.StateOrProvinceTextField, value) != true)) {
                    this.StateOrProvinceTextField = value;
                    this.RaisePropertyChanged("StateOrProvinceText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://goodmanmfg.com/GMC/WebService/DataQualityService/Rest", ConfigurationName="DataQualityService.IDataQualityServiceRest")]
    public interface IDataQualityServiceRest {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://goodmanmfg.com/GMC/WebService/DataQualityService/Rest/IDataQualityServiceR" +
            "est/Execute", ReplyAction="http://goodmanmfg.com/GMC/WebService/DataQualityService/Rest/IDataQualityServiceR" +
            "est/ExecuteResponse")]
        DPO.Domain.DataQualityService.DataQualityResponse Execute(DPO.Domain.DataQualityService.DataQualityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://goodmanmfg.com/GMC/WebService/DataQualityService/Rest/IDataQualityServiceR" +
            "est/Execute", ReplyAction="http://goodmanmfg.com/GMC/WebService/DataQualityService/Rest/IDataQualityServiceR" +
            "est/ExecuteResponse")]
        System.Threading.Tasks.Task<DPO.Domain.DataQualityService.DataQualityResponse> ExecuteAsync(DPO.Domain.DataQualityService.DataQualityRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataQualityServiceRestChannel : DPO.Domain.DataQualityService.IDataQualityServiceRest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataQualityServiceRestClient : System.ServiceModel.ClientBase<DPO.Domain.DataQualityService.IDataQualityServiceRest>, DPO.Domain.DataQualityService.IDataQualityServiceRest {
        
        public DataQualityServiceRestClient() {
        }
        
        public DataQualityServiceRestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataQualityServiceRestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataQualityServiceRestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataQualityServiceRestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DPO.Domain.DataQualityService.DataQualityResponse Execute(DPO.Domain.DataQualityService.DataQualityRequest request) {
            return base.Channel.Execute(request);
        }
        
        public System.Threading.Tasks.Task<DPO.Domain.DataQualityService.DataQualityResponse> ExecuteAsync(DPO.Domain.DataQualityService.DataQualityRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://goodmanmfg.com/GMC/WebService/DataQualityService", ConfigurationName="DataQualityService.IDataQualityService")]
    public interface IDataQualityService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://goodmanmfg.com/GMC/WebService/DataQualityService/IDataQualityService/Execu" +
            "te", ReplyAction="http://goodmanmfg.com/GMC/WebService/DataQualityService/IDataQualityService/Execu" +
            "teResponse")]
        DPO.Domain.DataQualityService.DataQualityResponse Execute(DPO.Domain.DataQualityService.DataQualityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://goodmanmfg.com/GMC/WebService/DataQualityService/IDataQualityService/Execu" +
            "te", ReplyAction="http://goodmanmfg.com/GMC/WebService/DataQualityService/IDataQualityService/Execu" +
            "teResponse")]
        System.Threading.Tasks.Task<DPO.Domain.DataQualityService.DataQualityResponse> ExecuteAsync(DPO.Domain.DataQualityService.DataQualityRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataQualityServiceChannel : DPO.Domain.DataQualityService.IDataQualityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataQualityServiceClient : System.ServiceModel.ClientBase<DPO.Domain.DataQualityService.IDataQualityService>, DPO.Domain.DataQualityService.IDataQualityService {
        
        public DataQualityServiceClient() {
        }
        
        public DataQualityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataQualityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataQualityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataQualityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DPO.Domain.DataQualityService.DataQualityResponse Execute(DPO.Domain.DataQualityService.DataQualityRequest request) {
            return base.Channel.Execute(request);
        }
        
        public System.Threading.Tasks.Task<DPO.Domain.DataQualityService.DataQualityResponse> ExecuteAsync(DPO.Domain.DataQualityService.DataQualityRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://goodmanmfg.com/GMC/WebService/DataQualityService/Json", ConfigurationName="DataQualityService.IDataQualityServiceJson")]
    public interface IDataQualityServiceJson {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://goodmanmfg.com/GMC/WebService/DataQualityService/Json/IDataQualityServiceJ" +
            "son/Execute", ReplyAction="http://goodmanmfg.com/GMC/WebService/DataQualityService/Json/IDataQualityServiceJ" +
            "son/ExecuteResponse")]
        DPO.Domain.DataQualityService.DataQualityResponse Execute(DPO.Domain.DataQualityService.DataQualityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://goodmanmfg.com/GMC/WebService/DataQualityService/Json/IDataQualityServiceJ" +
            "son/Execute", ReplyAction="http://goodmanmfg.com/GMC/WebService/DataQualityService/Json/IDataQualityServiceJ" +
            "son/ExecuteResponse")]
        System.Threading.Tasks.Task<DPO.Domain.DataQualityService.DataQualityResponse> ExecuteAsync(DPO.Domain.DataQualityService.DataQualityRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataQualityServiceJsonChannel : DPO.Domain.DataQualityService.IDataQualityServiceJson, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataQualityServiceJsonClient : System.ServiceModel.ClientBase<DPO.Domain.DataQualityService.IDataQualityServiceJson>, DPO.Domain.DataQualityService.IDataQualityServiceJson {
        
        public DataQualityServiceJsonClient() {
        }
        
        public DataQualityServiceJsonClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataQualityServiceJsonClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataQualityServiceJsonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataQualityServiceJsonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DPO.Domain.DataQualityService.DataQualityResponse Execute(DPO.Domain.DataQualityService.DataQualityRequest request) {
            return base.Channel.Execute(request);
        }
        
        public System.Threading.Tasks.Task<DPO.Domain.DataQualityService.DataQualityResponse> ExecuteAsync(DPO.Domain.DataQualityService.DataQualityRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
    }
}
